### ISSUE TITLE
No longer working as of V10

### ISSUE THREAD

**Issue by 9Volt1** [HadaIonut/Foundry-Markdown-Importer#17]
foundry.js:747 Error: NPCData Model Validation Errors
[NPCData.resources]: Model Validation Errors
[NPCData.resources.legact]: Model Validation Errors
[NPCData.resources.legact.value]: must be an integer
[NPCData.resources.legact.max]: must be an integer
[NPCData.resources.legres]: Model Validation Errors
[NPCData.resources.legres.value]: must be an integer
[NPCData.resources.legres.max]: must be an integer
[Detected 2 packages: system:dnd5e, Tetra-Cube-Importer]
    at SchemaField._validateType (commons.js:4098:15)
    at SchemaField.validate (commons.js:3824:37)
    at NPCData.validate (commons.js:5492:35)
    at new DataModel (commons.js:5269:26)
    at new NPCData (npc.mjs:43:16)
    at SystemDataField.initialize (commons.js:4814:25)
    at Actor5e._initialize (commons.js:5408:29)
    at Actor5e._initialize (foundry.js:13087:11)
    at new DataModel (commons.js:5270:12)
    at new ClientDocumentMixin (foundry.js:13053:5)
    at new Actor (foundry.js:16292:1)
    at new Actor5e (actor.mjs:10:16)
    at ClientDatabaseBackend._preCreateDocumentArray (foundry.js:12525:15)
    at ClientDatabaseBackend._createDocuments (foundry.js:12459:33)
    at ClientDatabaseBackend.create (commons.js:6738:24)
    at async Actor.createDocuments (commons.js:6110:23)
    at async Actor.create (commons.js:6233:23)
    at async actorCreator (ActorCreator.js:323:15)
onError @ foundry.js:747
foundry.js:59187 NPCData Model Validation Errors
[NPCData.resources]: Model Validation Errors
[NPCData.resources.legact]: Model Validation Errors
[NPCData.resources.legact.value]: must be an integer
[NPCData.resources.legact.max]: must be an integer
[NPCData.resources.legres]: Model Validation Errors
[NPCData.resources.legres.value]: must be an integer
[NPCData.resources.legres.max]: must be an integer
[Detected 2 packages: system:dnd5e, Tetra-Cube-Importer]
fetch @ foundry.js:59187
foundry.js:59187 There has been an error while creating Shield Masters
fetch @ foundry.js:59187
ItemCreator.js:221 TypeError: Cannot read properties of undefined (reading 'createEmbeddedDocuments')
    at itemCreator (ItemCreator.js:218:17)
    at abilitiesAdder (ItemCreator.js:235:13)
    at actorCreator (ActorCreator.js:334:30)
itemCreator @ ItemCreator.js:221
foundry.js:59187 There has been an error while creating Bodyguard
fetch @ foundry.js:59187
4ItemCreator.js:221 TypeError: Cannot read properties of undefined (reading 'createEmbeddedDocuments')
    at itemCreator (ItemCreator.js:218:17)
    at abilitiesAdder (ItemCreator.js:235:13)
    at async actorCreator (ActorCreator.js:334:24)
itemCreator @ ItemCreator.js:221
ItemCreator.js:110 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createEmbeddedDocuments')
[Detected 1 package: Tetra-Cube-Importer]
    at spellsAdder (ItemCreator.js:110:15)
    at async actorCreator (ActorCreator.js:336:21)
foundry.js:59187 There has been an error while creating Longbow
fetch @ foundry.js:59187
foundry.js:59187 There has been an error while creating Spear
fetch @ foundry.js:59187
foundry.js:59187

**Comment by RandomLegend** [comment]
I get those errors aswell, some statblocks work fine, some ot hers won't
